### ISSUE TITLE
Pixel Art Shader Renderer / Aesthetic Checklist

### ISSUE THREAD

**Issue by janfic** [janfic/parts#2]
Avoid / Enforce:
- [x] No Free Rotation ( Must be divisor of 360 )
- [x] Only rotate on single axis
- [x] Free Scaling ( Steps only )
- [ ] Minimum Animation Frames
- [ ] Changing of lighting ( meh )
- [x] Constant Perspective / Rare Discreet Perspective Changes

More Pixel Art Feel:
- [x] Basic Cel Shader
- [x] Bordered Objects ( Non Landscape )
     - Solid Border
     - Colored Border
- [x] Strict Palette Mapping / Changing
- [x] Dithering

Models
- [x] Experiment with Voxel Models?
